[WIP][cdc-pipeline-connector][mysql] Introduce mysql cdc pipeline DataSource
ververica/flink-cdc-connectors pull request #2782
Opened 2023-11-30 02:28 UTC by Jiabao-Sun

Introduce mysql cdc pipeline DataSource

Resolve #2647.

2023-11-30 15:29 UTC, leonardBang reviewed
Thanks @Jiabao-Sun for the great work, I left some comments

2023-11-30 15:29 UTC, leonardBang commented on flink-cdc-common/src/main/java/com/ververica/cdc/common/event/EventDeserializer.java
> +/** Deserializer to deserialize given record to {@link Event}. */
Could be a public interface here

2023-11-30 15:29 UTC, leonardBang commented on flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/com/ververica/cdc/connectors/mysql/factory/MySqlDataFactory.java
> +public class MySqlDataFactory implements DataSourceFactory {
MySqlDataSourceFactory ? we may add MySqlDataSinkFactory later

2023-11-30 15:29 UTC, leonardBang commented on flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/com/ververica/cdc/connectors/mysql/factory/MySqlDataFactory.java
> +                        // TODO: .chunkKeyColumn()
we can create an issue to support chunKeyColumn in table level in mysql cdc connector

2023-11-30 15:29 UTC, leonardBang commented on flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/com/ververica/cdc/connectors/mysql/factory/MySqlDataFactory.java
> +            case SCAN_STARTUP_MODE_VALUE_TIMESTAMP:
note: All of these mode need to send create table event firstly

2023-11-30 15:29 UTC, leonardBang commented on flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/com/ververica/cdc/connectors/mysql/source/MySqlDataSourceOptions.java
> +                            "Table names of the MySQL tables to monitor. Regular expressions are supported. eg. adb.*, bdb.user_table_[0-9]+, [app|web]_order_.*");
could you add escape character explanation in description? and we can also explain the table id mapping relation here, mysql's database name should map to our schemaName, mysql's table name should map to our tableName

2023-11-30 15:29 UTC, leonardBang commented on flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/com/ververica/cdc/connectors/mysql/source/MySqlMetadataAccessor.java
> +
could you add some java doc for the three methods? the note could contains the table path mapping relation

2023-11-30 15:29 UTC, leonardBang commented on flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/com/ververica/cdc/connectors/mysql/utils/MySqlTypeUtils.java
> +                return column.length() == 1 ? DataTypes.BOOLEAN() : DataTypes.TINYINT();
We can introduce a `treat-tinyint1-as-boolean` config for mysql data source, a `TINYINT (1)` type in mysql can store value `2`,`3` too.

2023-11-30 15:29 UTC, leonardBang commented on flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/com/ververica/cdc/connectors/mysql/utils/MySqlTypeUtils.java
> +            case TIMESTAMP:
TIMESTAMP should map to `TIMESTAMP_LTZ` if IIUC, we map it wrong in mysql cdc connector, it's better if we can change it in our first version.

2023-11-30 15:29 UTC, leonardBang commented on flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/resources/META-INF/services/com.ververica.cdc.common.factories.Factory
> +# Licensed to the Apache Software Foundation (ASF) under one or more
minor: Ververica copyright

2023-11-30 15:29 UTC, leonardBang commented on flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/resources/pipeline-test.yaml
> +#  capture-new-tables: true
We can release this feature in next release version, I'm worried we can not test well under current status

2023-11-30 15:29 UTC, leonardBang commented on flink-cdc-connect/flink-cdc-source-connectors/flink-connector-debezium/src/main/java/com/ververica/cdc/debezium/event/DebeziumEventDeserializationSchema.java
> +    // SerializedLambdas (MSHADE-260).
👍🏻 for the detailed note

2023-12-03 03:41 UTC, leonardBang commented on flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/resources/ddl/column_type_test_mysql8.sql
> +) DEFAULT CHARSET=utf8;
Could we refer[1] to cover more types?
[1] https://github.com/ververica/flink-cdc-connectors/blob/4843ab2432fe77d3a019f8002ec765cf78e42a88/flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/resources/ddl/column_type_test.sql#L55

2023-12-03 04:07 UTC, leonardBang commented on flink-cdc-connect/flink-cdc-source-connectors/flink-connector-debezium/src/main/java/com/ververica/cdc/debezium/event/DebeziumEventDeserializationSchema.java
> +                return convertToTimestamp(serverTimeZone);
After we support convert mysql timestamp to our timestamp_ltz, we do not need serverTimezone anymore for mysql datetime ?

2023-12-04 10:00 UTC, lvyanquan requested changes

2023-12-04 10:00 UTC, lvyanquan commented on flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/com/ververica/cdc/connectors/mysql/utils/MySqlTypeUtils.java
> +                        : DataTypes.TIMESTAMP_LTZ();
DataTypes.TIMESTAMP() will be of TimestampType.DEFAULT_PRECISION, which is 6, we should set to 0 to be consistent with DebeziumSchemaDataTypeInference#infer method.

2023-12-05 02:01 UTC, ruanhang1993 approved these changes
LGTM.

2023-12-05 02:13 UTC, merged